-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("qs")
    hl.exec_cmd(scriptsDir .. "/KeybindsLayoutInit.sh")
    hl.exec_cmd("blueman-applet")
end)
