-- Commands and Apps to be executed at launch (vendor defaults)

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local scriptsDir = HOME .. "/.config/hypr/scripts"
local UserScripts = HOME .. "/.config/hypr/UserScripts"

local wallDIR = HOME .. "/Pictures/wallpapers"
local lock = scriptsDir .. "/LockScreen.sh"
local SwwwRandom = UserScripts .. "/WallpaperAutoChange.sh"
local livewallpaper = "\"\""

-- wallpaper stuff 
--exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

-- wallpaper random
--exec-once = $SwwwRandom $wallDIR # random wallpaper switcher every 30 minutes

-- Startup

-- Initialize Drop Down terminal - See Bug#810 https://github.com/JaKooLit/Hyprland-Dots/issues/810#issuecomment-3351947644

-- Polkit (Polkit Gnome / KDE)

-- starup apps
-- exec-once = hyprpm reload -n   
--exec-once = ags
--exec-once = ags
--exec-once = blueman-applet
--exec-once = rog-control-center
-- exec-once = qs # quickshell AGS Desktop Overview alternative

--clipboard manager

-- Rainbow borders

-- Starting hypridle to start hyprlock

-- Resume Hyprsunset if state is "on" from previous session

-- Here are list of features available but disabled by default
-- exec-once = awww-daemon --format xrgb && awww img $HOME/Pictures/wallpapers/mecha-nostalgia.png  # persistent wallpaper

--gnome polkit for nixos
--exec-once = $scriptsDir/Polkit-NixOS.sh

-- xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
--exec-once = $scriptsDir/PortalHyprland.sh

hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon --format xrgb")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd(scriptsDir .. "/KeybindsLayoutInit.sh")
    hl.exec_cmd("$HOME/.config/hypr/scripts/Dropterminal.sh kitty &")
    hl.exec_cmd(scriptsDir .. "/Polkit.sh")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("nm-tray")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(UserScripts .. "/RainbowBorders.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(scriptsDir .. "/Hyprsunset.sh init")
end)

