-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- Vendor defaults for window rules and layerrules
-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- NOTES: This is only for Hyprland > 0.48

-- note for ja: This should NOT be implemented on Debian and Ubuntu

-- windowrule - tags - add apps under appropriate tag to use the same settings
-- browser tags

-- notif tags

-- KooL settings tag

-- terminal tags

-- email tags

-- project tags

-- screenshare tags

-- IM tags

-- game tags

-- gamestore tags

-- file-manager tags

-- wallpaper tags

-- multimedia tags

-- multimedia-video tags

-- settings tags

-- viewer tags

-- Some special override rules

-- POSITION
-- windowrule = center,floating:1 # warning, it cause even the menu to float and center.
--windowrule = move 72% 7%,title:^(Firefox)$ 

-- windowrule to avoid idle for fullscreen apps
--windowrule = idleinhibit fullscreen, class:^(*)$
--windowrule = idleinhibit fullscreen, title:^(*)$

-- windowrule move to workspace
--windowrule = workspace 1, tag:email*
--windowrule = workspace 2, tag:browser*
--windowrule = workspace 3, class:^([Tt]hunar)$
--windowrule = workspace 3, tag:projects*
--windowrule = workspace 5, tag:gamestore*
--windowrule = workspace 7, tag:im*
--windowrule = workspace 8, tag:games*

-- windowrule move to workspace (silent)
--windowrule = workspace 4 silent, tag:screenshare*
--windowrule = workspace 6 silent, class:^(virt-manager)$
--windowrule = workspace 6 silent, class:^(.virt-manager-wrapped)$
--windowrule = workspace 9 silent, tag:multimedia*
--
-- FLOAT
--windowrule = float, class:^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$
--windowrule = float, title:^(Firefox)$

-- windowrule - ######### float popups and dialogue #######

-- END of float popups and dialogue #######

-- OPACITY

-- SIZE

--windowrule = size 25% 25%, title:^(Picture-in-Picture)$   
--windowrule = size 25% 25%, title:^(Firefox)$ 

-- PINNING
--windowrule = pin,title:^(Firefox)$ 

-- windowrule - extras

-- BLUR & FULLSCREEN

--This not gonna take the focus to the window that appears when hovering over some of the parts of the IntelliJ Products 

--This will gonna make the VS Code bluer like other apps 

--windowrule = bordercolor rgb(EE4B55) rgb(880808), fullscreen:1
--windowrule = bordercolor rgb(282737) rgb(1E1D2D), floating:1
--windowrule = opacity 0.8 0.8, pinned:1

-- LAYER RULES

--layerrule = ignorealpha 0.5, tag:notif*

--layerrule = ignorezero, class:^([Rr]ofi)$
--layerrule = blur, class:^([Rr]ofi)$
--layerrule = unset,class:^([Rr]ofi)$
--layerrule = ignorezero, <rofi>

--layerrule = ignorezero, overview
--layerrule = blur, overview
-- --- Auto-generated window rules ---
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        class = "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-3",
    match = {
        class = "^(chrome-.+-Default)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-4",
    match = {
        class = "^([Cc]hromium)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-5",
    match = {
        class = "^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-6",
    match = {
        class = "^(Brave-browser(-beta|-dev|-unstable)?)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-7",
    match = {
        class = "^([Tt]horium-browser|[Cc]achy-browser)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-8",
    match = {
        class = "^(zen-alpha|zen)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name = "windowrule-9",
    match = {
        class = "^(swaync-control-center|swaync-notification-window|swaync-client|class)$",
    },
    tag = "+notif",
})

hl.window_rule({
    name = "windowrule-10",
    match = {
        title = "^(KooL Quick Cheat Sheet)$",
    },
    tag = "+KooL_Cheat",
})

hl.window_rule({
    name = "windowrule-11",
    match = {
        title = "^(KooL Hyprland Settings)$",
    },
    tag = "+KooL_Settings",
})

hl.window_rule({
    name = "windowrule-12",
    match = {
        class = "^(nwg-displays|nwg-look)$",
    },
    tag = "+KooL-Settings",
})

hl.window_rule({
    name = "windowrule-13",
    match = {
        class = "^(Alacritty|kitty|kitty-dropterm)$",
    },
    tag = "+terminal",
})

hl.window_rule({
    name = "windowrule-14",
    match = {
        class = "^([Tt]hunderbird|org.gnome.Evolution)$",
    },
    tag = "+email",
})

hl.window_rule({
    name = "windowrule-15",
    match = {
        class = "^(eu.betterbird.Betterbird)$",
    },
    tag = "+email",
})

hl.window_rule({
    name = "windowrule-16",
    match = {
        class = "^(codium|codium-url-handler|VSCodium)$",
    },
    tag = "+projects",
})

hl.window_rule({
    name = "windowrule-17",
    match = {
        class = "^(VSCode|code-url-handler)$",
    },
    tag = "+projects",
})

hl.window_rule({
    name = "windowrule-18",
    match = {
        class = "^(jetbrains-.+)$",
    },
    tag = "+projects",
})

hl.window_rule({
    name = "windowrule-19",
    match = {
        class = "^(com.obsproject.Studio)$",
    },
    tag = "+screenshare",
})

hl.window_rule({
    name = "windowrule-20",
    match = {
        class = "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$",
    },
    tag = "+im",
})

hl.window_rule({
    name = "windowrule-21",
    match = {
        class = "^([Ff]erdium)$",
    },
    center = true,
    float = true,
    size = "60% = 70%",
    tag = "+im",
})

hl.window_rule({
    name = "windowrule-22",
    match = {
        class = "^([Ww]hatsapp-for-linux)$",
    },
    tag = "+im",
})

hl.window_rule({
    name = "windowrule-23",
    match = {
        class = "^(ZapZap|com.rtosta.zapzap)$",
    },
    tag = "+im",
})

hl.window_rule({
    name = "windowrule-24",
    match = {
        class = "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$",
    },
    tag = "+im",
})

hl.window_rule({
    name = "windowrule-25",
    match = {
        class = "^(teams-for-linux)$",
    },
    tag = "+im",
})

hl.window_rule({
    name = "windowrule-26",
    match = {
        class = "^(im.riot.Riot|Element)$",
    },
    tag = "+im",
})

hl.window_rule({
    name = "windowrule-27",
    match = {
        class = "^(gamescope)$",
    },
    tag = "+games",
})

hl.window_rule({
    name = "windowrule-28",
    match = {
        class = "^(steam_app_\\d+)$",
    },
    tag = "+games",
})

hl.window_rule({
    name = "windowrule-29",
    match = {
        class = "^([Ss]team)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    name = "windowrule-30",
    match = {
        title = "^([Ll]utris)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    name = "windowrule-31",
    match = {
        class = "^(com.heroicgameslauncher.hgl)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    name = "windowrule-32",
    match = {
        class = "^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$",
    },
    tag = "+file-manager",
})

hl.window_rule({
    name = "windowrule-33",
    match = {
        class = "^(app.drey.Warp)$",
    },
    tag = "+file-manager",
})

hl.window_rule({
    name = "windowrule-34",
    match = {
        class = "^([Ww]aytrogen)$",
    },
    tag = "+wallpaper",
})

hl.window_rule({
    name = "windowrule-35",
    match = {
        class = "^([Aa]udacious)$",
    },
    tag = "+multimedia",
})

hl.window_rule({
    name = "windowrule-36",
    match = {
        class = "^([Mm]pv|vlc)$",
    },
    tag = "+multimedia_video",
})

hl.window_rule({
    name = "windowrule-37",
    match = {
        title = "^(ROG Control)$",
    },
    center = true,
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-38",
    match = {
        class = "^(wihotspot(-gui)?)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-39",
    match = {
        class = "^([Bb]aobab|org.gnome.[Bb]aobab)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-40",
    match = {
        class = "^(gnome-disks|wihotspot(-gui)?)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-41",
    match = {
        title = "(Kvantum Manager)",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-42",
    match = {
        class = "^(file-roller|org.gnome.FileRoller)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-43",
    match = {
        class = "^(nm-applet|nm-connection-editor|blueman-manager)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-44",
    match = {
        class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    center = true,
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-45",
    match = {
        class = "^(qt5ct|qt6ct|[Yy]ad)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-46",
    match = {
        class = "(xdg-desktop-portal-gtk)",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-47",
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-48",
    match = {
        class = "^([Rr]ofi)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name = "windowrule-49",
    match = {
        class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    name = "windowrule-50",
    match = {
        class = "^(evince)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    name = "windowrule-51",
    match = {
        class = "^(eog|org.gnome.Loupe)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    name = "windowrule-52",
    match = {
        tag = "multimedia_video*",
    },
    no_blur = true,
    opacity = 1.0,
})

hl.window_rule({
    name = "windowrule-53",
    match = {
        tag = "KooL_Cheat*",
    },
    center = true,
    float = true,
    size = "65% = 90%",
})

hl.window_rule({
    name = "windowrule-54",
    match = {
        class = "([Tt]hunar)",
        title = "negative:(.*[Tt]hunar.*)",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name = "windowrule-55",
    match = {
        tag = "KooL-Settings*",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name = "windowrule-56",
    match = {
        title = "^(Keybindings)$",
    },
    center = true,
})

hl.window_rule({
    name = "windowrule-57",
    match = {
        class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    center = true,
    size = "60% = 70%",
})

hl.window_rule({
    name = "windowrule-58",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    move = "72% = 7%",
    opacity = "0.95 0.75",
    pin = false,
})

hl.window_rule({
    name = "windowrule-59",
    match = {
        fullscreen = 1,
    },
    idle_inhibit = "fullscreen",
})

hl.window_rule({
    name = "windowrule-60",
    match = {
        tag = "wallpaper*",
    },
    float = true,
    opacity = "0.9 0.7",
    size = "70% = 70%",
})

hl.window_rule({
    name = "windowrule-61",
    match = {
        tag = "settings*",
    },
    float = true,
    opacity = "0.8 0.7",
    size = "70% = 70%",
})

hl.window_rule({
    name = "windowrule-62",
    match = {
        tag = "viewer*",
    },
    float = true,
    opacity = "0.82 0.75",
})

hl.window_rule({
    name = "windowrule-63",
    match = {
        class = "([Zz]oom|onedriver|onedriver-launcher)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-64",
    match = {
        class = "(org.gnome.Calculator)",
        title = "(Calculator)",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-65",
    match = {
        class = "^(mpv|com.github.rafostar.Clapper)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-66",
    match = {
        class = "^([Qq]alculate-gtk)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-67",
    match = {
        title = "^(Authentication Required)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name = "windowrule-68",
    match = {
        class = "(codium|codium-url-handler|VSCodium)",
        title = "negative:(.*codium.*|.*VSCodium.*)",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-69",
    match = {
        class = "^(com.heroicgameslauncher.hgl)$",
        title = "negative:(Heroic Games Launcher)",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-70",
    match = {
        class = "^([Ss]team)$",
        title = "negative:^([Ss]team)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-71",
    match = {
        title = "^(Add Folder to Workspace)$",
    },
    center = true,
    float = true,
    size = "70% = 60%",
})

hl.window_rule({
    name = "windowrule-72",
    match = {
        title = "^(Save As)$",
    },
    center = true,
    float = true,
    size = "70% = 60%",
})

hl.window_rule({
    name = "windowrule-73",
    match = {
        initial_title = "(Open Files)",
    },
    float = true,
    size = "70% = 60%",
})

hl.window_rule({
    name = "windowrule-74",
    match = {
        title = "^(SDDM Background)$",
    },
    center = true,
    float = true,
    size = "16% = 12%",
})

hl.window_rule({
    name = "windowrule-75",
    match = {
        tag = "browser*",
    },
    opacity = "0.99 0.8",
})

hl.window_rule({
    name = "windowrule-76",
    match = {
        tag = "projects*",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name = "windowrule-77",
    match = {
        tag = "im*",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    name = "windowrule-78",
    match = {
        tag = "multimedia*",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    name = "windowrule-79",
    match = {
        tag = "file-manager*",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name = "windowrule-80",
    match = {
        tag = "terminal*",
    },
    opacity = "0.9 0.7",
})

hl.window_rule({
    name = "windowrule-81",
    match = {
        class = "^(gedit|org.gnome.TextEditor|mousepad)$",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    name = "windowrule-82",
    match = {
        class = "^(deluge)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name = "windowrule-83",
    match = {
        class = "^(seahorse)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name = "windowrule-84",
    match = {
        class = "^(code)$",
    },
    opacity = 0.8,
    opacity = 0.9,
})

hl.window_rule({
    name = "windowrule-85",
    match = {
        tag = "games*",
    },
    fullscreen = false,
    no_blur = true,
})

hl.window_rule({
    name = "windowrule-86",
    match = {
        class = "^(jetbrains-*)",
    },
    no_initial_focus = true,
})

hl.window_rule({
    name = "windowrule-87",
    match = {
        title = "^(wind.*)$",
    },
    no_initial_focus = true,
})

-- --- Auto-generated layer rules ---
hl.layer_rule({
    name = "layerrule-1",
    match = {
        namespace = "rofi",
    },
    blur = true,
    -- TODO: manual review — disable "ignore_alpha" has no layer_rule directive analog
})

hl.layer_rule({
    name = "layerrule-2",
    match = {
        namespace = "notifications",
    },
    blur = true,
    -- TODO: manual review — disable "ignore_alpha" has no layer_rule directive analog
})

hl.layer_rule({
    name = "layerrule-3",
    match = {
        namespace = "quickshell:overview",
    },
    blur = true,
    -- TODO: manual review — disable "ignore_alpha" has no layer_rule directive analog
    ignore_alpha = 0.5,
})

