-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- as per Hyprland wiki: hyprland-qt-support provides a QML style for hypr* qt6 apps                                                         

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'roundess = 2' has no enclosing section

-- TODO: manual review — top-level key 'border_width = 0' has no enclosing section

-- TODO: manual review — top-level key 'reduce_motion = false' has no enclosing section
