-- Generated by nwg-displays on 2026-06-29 at 21:49:14. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "0x0",
    scale = "1.25",
})

