# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CDD3D6
background         #101111
cursor             #868E92

active_tab_foreground     #101111
active_tab_background     #CDD3D6
inactive_tab_foreground   #CDD3D6
inactive_tab_background   #101111

active_border_color   #CDD3D6
inactive_border_color #101111
bell_border_color     #23292D

color0      #38393A
color1		#23292D
color2		#2F373B
color3		#3C454A
color4		#485358
color5		#556167
color6		#556167
color7		#B0B8BC
color8		#7B8083
color9		#2E363C
color10		#3F494F
color11		#505C62
color12		#606E76
color13		#718189
color14		#718189
color15		#B0B8BC
