# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4D3EB
background         #151115
cursor             #B289AA

active_tab_foreground     #151115
active_tab_background     #F4D3EB
inactive_tab_foreground   #F4D3EB
inactive_tab_background   #151115

active_border_color   #F4D3EB
inactive_border_color #151115
bell_border_color     #3B192A

color0      #3C393D
color1		#3B192A
color2		#552F4E
color3		#653E7B
color4		#8C507D
color5		#9A565B
color6		#A76095
color7		#E7B7DA
color8		#A18099
color9		#4F2138
color10		#713F69
color11		#8653A4
color12		#BA6AA7
color13		#CE7379
color14		#DF80C6
color15		#E7B7DA
