-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- always refer to Hyprland wiki
-- https://wiki.hyprland.org/

-- Initial boot script enable to apply initial wallpapers, theming, new settings etc.
-- suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done
-- as long as the referrence file is present, this initial-boot.sh will not execute
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Sourcing external config files
local hyprconf = HOME .. "/.config/hypr/hyprconf" -- Hyprland conf include directory
local configs = hyprconf .. "/configs" -- Default Configs directory path
-- ## This is where you want to start tinkering 
local UserConfigs = hyprconf .. "/UserConfigs" -- User Configs directory path

-- Source: $configs/Keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.Keybinds")

-- Load vendor defaults, then user additions/overrides
-- Source: $configs/Startup_Apps.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.Startup_Apps")
-- Source: $UserConfigs/Startup_Apps.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.Startup_Apps")

-- Source: $UserConfigs/ENVariables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.ENVariables")

-- Source: $UserConfigs/Laptops.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.Laptops")
-- Source: $UserConfigs/LaptopDisplay.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.LaptopDisplay")

-- Load vendor defaults, then user additions
-- Source: $configs/WindowRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.WindowRules")
-- Source: $UserConfigs/WindowRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.WindowRules")

-- Source: $UserConfigs/UserDecorations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserDecorations")
-- Source: $UserConfigs/UserAnimations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserAnimations")
-- Source: $UserConfigs/UserKeybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserKeybinds")
-- Source: $UserConfigs/UserSettings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserSettings")
-- Source: $UserConfigs/01-UserDefaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs._01-UserDefaults")

-- nwg-displays
-- Source: $HOME/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.monitors")
-- Source: $hyprconf/workspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_hyprconf.workspaces")

-- hyprpm plugins
-- Source: $configs/plugins/hyprexpo.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.plugins.hyprexpo")

-- HyprMod managed settings
-- Source: /home/admin/.config/hypr/hyprland-gui.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-gui")

hl.on("hyprland.start", function()
    hl.exec_cmd("$HOME/.config/hypr/initial-boot.sh")
end)

