-- Hypridle 
-- Original config submitted by https://github.com/SherLock707                                                       
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local iDIR = "\"" .. HOME .. "/.config/swaync/images/ja.png\""

-- TODO: manual review — unknown section 'listener {' on line 15

-- TODO: manual review — unknown section 'listener {' on line 22

-- TODO: manual review — unknown section 'listener {' on line 29

-- TODO: manual review — unknown section 'listener {' on line 37

-- TODO: manual review — unknown section 'listener {' on line 44
-- on-resume = notify-send -i $iDIR "Welcome back " "Hello Dennis !!!"  # command to run when activity is detected after timeout has fired.
hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock", -- runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called) 
        -- unlock_cmd = killall hyprlock # kills hyprlock when unlocking (this is always run when "loginctl unlock-session" is called)
        before_sleep_cmd = "loginctl lock-session", -- ensures that the session is locked before going to sleep
        after_sleep_cmd = "hyprctl dispatch dpms on", -- turn of screen after sleep (not strictly necessary, but just in case)
        ignore_dbus_inhibit = false, -- whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    },
    -- turn off screen faster if session is already locked
    -- (disabled by default)
    -- Warn
    -- Screenlock
    -- Turn off screen 
    -- (disabled by default)
    -- Suspend # disabled by default
})

