-- Generated by HyprMod

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01Hz",
    position = "0x0",
    scale = "1",
    cm = "srgb",
})

hl.config({
    cursor = {
        hide_on_key_press = 1,
        inactive_timeout = 5,
    },
    decoration = {
        active_opacity = 1,
        dim_strength = 0.2,
        fullscreen_opacity = 0.95,
        inactive_opacity = 0.85,
        rounding = 10,
    },
    misc = {
        animate_manual_resizes = 1,
        animate_mouse_windowdragging = 1,
        focus_on_activate = 1,
    },
    -- Monitors
})

