-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- Hyprlock config for < 1080p monitor resolutions                                                         
-- Original config submitted by https://github.com/SherLock707

-- Sourcing colors generated by wallust
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: $HOME/.config/hypr/wallust/wallust-hyprland.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.wallust.wallust-hyprland")
local Scripts = HOME .. "/.config/hypr/scripts"

-- TODO: manual review — unknown section 'background {' on line 15
-- NOTE: use only 1 path
--path = screenshot   # screenshot of your desktop
--path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_modified # by wallpaper effects
-- all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations

-- TODO: manual review — unknown section 'label {' on line 36

-- TODO: manual review — unknown section 'label {' on line 48
--     text = cmd[update:1000] echo "$(date +"%H")"
--color = rgba(255, 185, 0, .8)

-- TODO: manual review — unknown section 'label {' on line 103

-- TODO: manual review — unknown section 'input-field {' on line 115

-- TODO: manual review — unknown section 'label {' on line 136

-- TODO: manual review — unknown section 'label {' on line 148

-- TODO: manual review — unknown section 'label {' on line 160

-- TODO: manual review — unknown section 'label {' on line 174
hl.config({
    general = {
        grace = 1,
        fractional_scaling = 2,
        immediate_render = true,
    },
    -- Date
    -- Hour-Time
    -- Minute-Time
    -- label {
    --     monitor =
    --     text = cmd[update:1000] echo "$(date +"%M")"
    --     #color = rgba(15, 10, 222, .8)
    --     color = $color12
    --     font_size = 150
    --     font_family = JetBrainsMono Nerd Font ExtraBold
    --     position = 0, -340
    --     halign = center
    --    valign = top
    -- }
    -- Seconds-Time
    --label {
    --    monitor =
    --#     text = cmd[update:1000] echo "$(date +"%S")"
    --    text = cmd[update:1000] echo "$(date +"%S %p")" #AM/PM
    --    color = $color11
    --    font_size = 32
    --    font_family = JetBrainsMono Nerd Font ExtraBold
    --    position = 0, -350
    --    halign = center
    --    valign = top
    --}
    -- Put a picture of choice here. Default is the current wallpaper
    --image {
    --    monitor =
    --    path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_current
    --    size = 160
    --    rounding = -1
    --    border_size = 0
    --    border_color = $color11
    --    rotate = 0
    --    reload_time = -1
    --    position = 0, 280
    --    halign = center
    --    valign = bottom
    -- USER
    -- INPUT FIELD
    -- Keyboard LAYOUT
    -- uptime
    -- battery information
    -- weather edit the scripts for locations
    -- weather scripts are located in ~/.config/hypr/UserScripts Weather.sh and/or Weather.py
    -- see https://github.com/JaKooLit/Hyprland-Dots/wiki/TIPS#%EF%B8%8F-weather-app-related-for-waybar-and-hyprlock
})

